// <auto-generated />
using Arkham.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arkham.API.Migrations
{
    [DbContext(typeof(ArkhamDbContext))]
    [Migration("20251121020020_AddFaction2Card")]
    partial class AddFaction2Card
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arkham.API.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackFlavor")
                        .HasColumnType("text");

                    b.Property<string>("BackImageSrc")
                        .HasColumnType("text");

                    b.Property<string>("BackText")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("DeckLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("DeckSize")
                        .HasColumnType("integer");

                    b.Property<bool>("DoubleSided")
                        .HasColumnType("boolean");

                    b.Property<bool>("Exceptional")
                        .HasColumnType("boolean");

                    b.Property<int?>("Faction2Id")
                        .HasColumnType("integer");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Flavor")
                        .HasColumnType("text");

                    b.Property<int?>("Health")
                        .HasColumnType("integer");

                    b.Property<bool>("HealthPerInvestigator")
                        .HasColumnType("boolean");

                    b.Property<string>("Illustrator")
                        .HasColumnType("text");

                    b.Property<string>("ImageSrc")
                        .HasColumnType("text");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<bool>("Myriad")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OctgnId")
                        .HasColumnType("text");

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.Property<bool>("Permanent")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RealName")
                        .HasColumnType("text");

                    b.Property<string>("RealSlot")
                        .HasColumnType("text");

                    b.Property<string>("RealText")
                        .HasColumnType("text");

                    b.Property<int?>("Sanity")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillAgility")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillCombat")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillIntellect")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillWild")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillWillpower")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .HasColumnType("text");

                    b.Property<string>("SubName")
                        .HasColumnType("text");

                    b.Property<int?>("SubTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int?>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Faction2Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("PackId");

                    b.HasIndex("SubTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Arkham.API.Entities.CardTrait", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("TraitId")
                        .HasColumnType("integer");

                    b.HasKey("CardId", "TraitId");

                    b.HasIndex("TraitId");

                    b.ToTable("CardTraits");
                });

            modelBuilder.Entity("Arkham.API.Entities.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelMax")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelMin")
                        .HasColumnType("integer");

                    b.Property<int?>("Limit")
                        .HasColumnType("integer");

                    b.Property<bool?>("Not")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("DeckOptions");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOptionFaction", b =>
                {
                    b.Property<int>("DeckOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.HasKey("DeckOptionId", "FactionId");

                    b.HasIndex("FactionId");

                    b.ToTable("DeckOptionFactions");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOptionTrait", b =>
                {
                    b.Property<int>("DeckOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("TraitId")
                        .HasColumnType("integer");

                    b.HasKey("DeckOptionId", "TraitId");

                    b.HasIndex("TraitId");

                    b.ToTable("DeckOptionTraits");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("DeckRequirements");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeckRequirementCardChoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckRequirementCardChoiceId");

                    b.ToTable("DeckRequirementCards");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementCardChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckRequirementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckRequirementId");

                    b.ToTable("DeckRequirementCardChoices");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementRandom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckRequirementId")
                        .HasColumnType("integer");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckRequirementId");

                    b.ToTable("DeckRequirementRandoms");
                });

            modelBuilder.Entity("Arkham.API.Entities.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("Arkham.API.Entities.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("Arkham.API.Entities.SubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubTypes");
                });

            modelBuilder.Entity("Arkham.API.Entities.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("Arkham.API.Entities.Card", b =>
                {
                    b.HasOne("Arkham.API.Entities.Faction", "Faction2")
                        .WithMany()
                        .HasForeignKey("Faction2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Arkham.API.Entities.Faction", "Faction")
                        .WithMany("Cards")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arkham.API.Entities.Pack", "Pack")
                        .WithMany("Cards")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkham.API.Entities.SubType", "SubType")
                        .WithMany("Cards")
                        .HasForeignKey("SubTypeId");

                    b.HasOne("Arkham.API.Entities.CardType", "Type")
                        .WithMany("Cards")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Faction2");

                    b.Navigation("Pack");

                    b.Navigation("SubType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Arkham.API.Entities.CardTrait", b =>
                {
                    b.HasOne("Arkham.API.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkham.API.Entities.Trait", "Trait")
                        .WithMany()
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOption", b =>
                {
                    b.HasOne("Arkham.API.Entities.Card", "Card")
                        .WithMany("DeckOptions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOptionFaction", b =>
                {
                    b.HasOne("Arkham.API.Entities.DeckOption", "DeckOption")
                        .WithMany()
                        .HasForeignKey("DeckOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkham.API.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckOption");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckOptionTrait", b =>
                {
                    b.HasOne("Arkham.API.Entities.DeckOption", "DeckOption")
                        .WithMany()
                        .HasForeignKey("DeckOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkham.API.Entities.Trait", "Trait")
                        .WithMany()
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckOption");

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirement", b =>
                {
                    b.HasOne("Arkham.API.Entities.Card", "Card")
                        .WithOne("DeckRequirement")
                        .HasForeignKey("Arkham.API.Entities.DeckRequirement", "CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementCard", b =>
                {
                    b.HasOne("Arkham.API.Entities.DeckRequirementCardChoice", "DeckRequirementCardChoice")
                        .WithMany("Cards")
                        .HasForeignKey("DeckRequirementCardChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckRequirementCardChoice");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementCardChoice", b =>
                {
                    b.HasOne("Arkham.API.Entities.DeckRequirement", "DeckRequirement")
                        .WithMany("CardChoices")
                        .HasForeignKey("DeckRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckRequirement");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementRandom", b =>
                {
                    b.HasOne("Arkham.API.Entities.DeckRequirement", "DeckRequirement")
                        .WithMany("Randoms")
                        .HasForeignKey("DeckRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckRequirement");
                });

            modelBuilder.Entity("Arkham.API.Entities.Card", b =>
                {
                    b.Navigation("DeckOptions");

                    b.Navigation("DeckRequirement");
                });

            modelBuilder.Entity("Arkham.API.Entities.CardType", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirement", b =>
                {
                    b.Navigation("CardChoices");

                    b.Navigation("Randoms");
                });

            modelBuilder.Entity("Arkham.API.Entities.DeckRequirementCardChoice", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Arkham.API.Entities.Faction", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Arkham.API.Entities.Pack", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Arkham.API.Entities.SubType", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
